 # 'id': id,
                # # 'titulo': titulo,
                # 'descricao':descricao,
                # # 'preco': preco,
                # 'data_anunciado': data_anunciado,
                # 'url': url,
                # 'portal': portal,
                # 'atualizacao_data': atualizacao_data,
                # 'cep': cep,
                # 'area_util': area_util,
                # 'area_total': area_total,
                # 'area': area,
                # 'cidade': cidade,
                # 'estado': estado,
                # 'rua': rua,
                # 'bairro': bairro,
                # 'pais': pais,
                # 'quartos': quartos,
                # 'banheiros': banheiros,
                # 'suites': suites,
                # 'vagas': vagas,
                # 'proprietario': proprietario,
                # 'proprietario_id': proprietario_id,
                # 'proprietario_telefone': proprietario_telefone,
                # # 'anunciante': anunciante,
                # # 'anunciante_id': anunciante_id,
                # 'anunciante_telefone': anunciante_telefone,